### ISSUE TITLE
Regarding date time stamp

### ISSUE THREAD

**Issue by sid0312** [iperezx/sage-smoke-detection#4]
If we generate data using the sage_client.ipynb notebook we get a set of images in the attention folder.

Consider: 1650146394301354963-sample_current.jpg has the timestamp  1650146394301354963. 

This is in nanoseconds. Can you update it upto the code to give it in seconds (10 digits: 1650146394) i.e. , we don't need that much precision for upto nano seconds ?

**Comment by iperezx** [comment]
That is internal to Sage SDR so it will just need to be change externally per-use-case.
